name: Call Worktree Update

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

jobs:
  call_reusable_workflow:
    uses: HITSZ-OpenAuto/repos-management/.github/workflows/reusable_worktree_generate.yml@fix/unified-ci
    permissions:
      contents: write
      pull-requests: write

    with:
      # trigger_page_build == true only when pushing to main branch
      trigger_page_build: true

    secrets:
      PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
